# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: sespiros
email: sespiros@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
        My name is Spyros Seimenis and I am a well-rounded computer *security engineer and researcher* that specializes 
        in finding and reporting bugs through reverse engineering and source code auditing. I have worked
        with numerous clients worldwide in various fields like mobile device platforms, IoT and banking and
        helped them secure their products. Having a software engineering background, I also provide consultation 
        on best coding practices that promote the writing of more secure code.

        I hold an MSc in Computer Science from the Computer Engineering and Informatics department of University of Patras.
        My main areas of research interest there were cryptography, programming languages (topics such as compilers, algorithms 
        and data structures, parallel processing, software engineering), communication networks, topics on theory of computation 
        and computer graphics. I did my thesis on penetration testing methodologies, techniques, processes and reporting, covering 
        the technical and business aspects of a penetration test with the final goal of producing a solid and helpful report.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sespiros.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sespiros
github_username:  sespiros

markdown: kramdown

tracking_id: G-DG5LVB63C5

footer: yes
footer_url: https://sespiros.github.io
footer_text: "🄯 2023"

sass:
    style: compressed
    sass_dir: _sass

# nav:
#     - name: "About"
#       link: "/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
